# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Movie.create(date: Date.new(2019, 11, 02).to_s(:db), title: "The Irishman", year: 2019, director: "Martin Scorsese", movie_img: "https://upload.wikimedia.org/wikipedia/en/8/80/The_Irishman_poster.jpg", stars: "4444", notes: "Stellar cast, director, screenplay, and a few years late. That being said it is great. De Niro, Pacino, Pesci, and Scorsese all deliver. After Hoffa is killed the last hour seems to drag a little bit. The de-aging works well.")
Movie.create(date: Date.new(2019, 11, 02).to_s(:db), title: "The Dark Knight", year: 2008, director: "Christopher Nolan", movie_img: "https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg", stars: "55555", notes: "It is not perfect and is a little long. Definitely a great comic book movie though thanks mainly to Heath Ledger as the Joker. He does a flawless job and steals every scene. Eckhart, Oldman, Freeman, Caine are all wonderful in their roles. Until this viewing I never knew that Gordon is driving the van when Joker is trying to kill Dent. That being said the guy next to Gordon has incredible dialogue during that sequence. I'll leave it at that for now!")
Movie.create(date: Date.new(2019, 11, 03).to_s(:db), title: "The Dark Knight Rises", year: 2012, director: "Christopher Nolan", movie_img: "https://upload.wikimedia.org/wikipedia/en/8/83/Dark_knight_rises_poster.jpg", stars: "4444", notes: "The movie where Christian Bale does the best job in his role in my opinion.  Selina Kyle and her motives add fun storylines which I think are the best part of the movie.  That being said this is the final movie in a trilogy but does not feel like it belongs or comes after the first two.  James Gordon feels like he could be a completely different character, Rachel storyline ends the Alfred/Bruce relationship which I do not dig.  JGL gets a lot of screen time, does a great job and this feels like his movie which is weird considering the title.  Finally it is definitely too long, there's too much of Gotham in Peril.")
Movie.create(date: Date.new(2019, 11, 17).to_s(:db), title: "A Colt Is My Passport", year: 1967, director: "Takashi Nomura", movie_img: "https://upload.wikimedia.org/wikipedia/en/2/27/A_Colt_Is_My_Passport_poster.jpg", stars: "4444", notes: "A brilliant Noir / Western blend. Director Takashi Nomura pulls from Sergio Leone's Man With No Name Trilogy. Lead actor Joe Shishido pulls from Clint Eastwood but might say more.  Awesome showdown at the end up there with the sequences in Yojimbo, A Fistful of Dollars, and The Good, The Bad & the Ugly.")

Episode.create(date: Date.new(2019, 11, 18).to_s(:db), episode_name: "Tennis the Menace", show_name: "The Simpsons", season_episode_num: 12.12, season_img: "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Simpsons_-_The_12th_Season.jpg", stars: "333", notes: "Tennis greats have cameo at end. Bart as Oedipus with Homer's head on the wall. Lisa as Homer's therapist.")
Episode.create(date: Date.new(2019, 11, 19).to_s(:db), episode_name: "Day of the Jackanapes", show_name: "The Simpsons", season_episode_num: 12.13, season_img: "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Simpsons_-_The_12th_Season.jpg", stars: "333", notes: "Sideshow Bob is back and lands a job at Springfield to brainwash Bart.")
Episode.create(date: Date.new(2019, 11, 20).to_s(:db), episode_name: "New Kids on the Blecch", show_name: "The Simpsons", season_episode_num: 12.14, season_img: "https://upload.wikimedia.org/wikipedia/en/1/1d/The_Simpsons_-_The_12th_Season.jpg", stars: "333", notes: "The boy band episode featuring N'Sync.")
